services:
    fuseki:
        image: ${IMAGE_VERSION}
        user: "${UID}:${GID}"
        restart: "no"
        profiles: ["${CONTAINER_NAME}"]
        ports:
        -   "${TS_PORT}:3030"
        container_name: ${CONTAINER_NAME}
        volumes:
        -   fuseki_data:/fuseki
        environment:
        -   ADMIN_PASSWORD=${TS_PASSWORD}
volumes:
    fuseki_data:
        driver: local
