services:
    postgres:
        image: ${IMAGE_VERSION}
        container_name: ${CONTAINER_NAME}
        restart: "no"
        profiles: ["${SPEC}.postgres"]
        ports:
        -   "${POSTGRES_PORT:-5432}:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
            POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-scram-sha-256}
        volumes:
        -   postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
        driver: local
