site_name: GraFlo
site_url: https://growgraph.github.io/graflo
repo_url: https://github.com/growgraph/graflo
repo_name: growgraph/graflo
copyright: Copyright &copy; 2025 GrowGraph
theme:
    name: material
    user_color_mode_toggle: true
    palette:
    -   scheme: default
        primary: green
        accent: deep purple
        toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
    -   scheme: slate
        primary: deep purple
        accent: yellow
        toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    logo: assets/project_logo.png
    icon:
        repo: fontawesome/brands/github
    favicon: assets/favicon.ico
plugins:
-   search
-   glightbox
-   gen-files:
        scripts:
        -   docs/gen_pages.py
-   literate-nav
-   table-reader: []
-   mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                    extra:
                        show_root_full_path: true
                        show_docstring: true
                        show_source: true
                        show_root_toc_entry: false
                        docstring_style: google
                        show_submodules: true
                        show_category_heading: true
                        show_if_no_docstring: true
                        setup_commands:
                        -   import sys
                        -   sys.path.append('.')
nav:
-   Home: index.md
-   Getting Started:
    -   Installation: getting_started/installation.md
    -   Quick Start: getting_started/quickstart.md
    -   Creating a Schema: getting_started/creating_schema.md
-   Concepts: concepts/index.md
-   Examples:
    -   Examples Index: examples/index.md
    -   1 - Ingest Multiple Tabular Sources (CSV, ArangoDB): examples/example-1.md
    -   2 - JSON with Edges between the same Vertex Type (ArangoDB): examples/example-2.md
    -   3 - CSV with Edge Weights and Multiple Relations (Neo4j): examples/example-3.md
    -   4 - Dynamic Relations from Keys (Neo4j): examples/example-4.md
    -   5 - Ingesting Data from PostgreSQL Tables: examples/example-5.md
#    -   6 - REST API Data Source: examples/example-6.md
-   API Reference: reference/
-   Contributing: contributing.md
markdown_extensions:
-   pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
-   pymdownx.inlinehilite
-   pymdownx.snippets
-   pymdownx.superfences:
        custom_fences:
        -   name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
-   attr_list
-   md_in_html
-   admonition
-   codehilite
-   footnotes
-   meta
-   pymdownx.blocks.caption
-   pymdownx.details
-   pymdownx.tabbed
-   pymdownx.highlight
-   pymdownx.emoji
-   pymdownx.tasklist
-   pymdownx.keys
-   pymdownx.snippets
-   pymdownx.magiclink
-   pymdownx.betterem
-   pymdownx.caret
-   pymdownx.tilde
-   pymdownx.mark
-   pymdownx.smartsymbols
-   pymdownx.arithmatex
-   pymdownx.progressbar
-   pymdownx.escapeall
-   toc:
        permalink: true
