services:
    falkordb:
        image: ${IMAGE_VERSION}
        container_name: ${CONTAINER_NAME}
        restart: "no"
        profiles: ["${SPEC}.falkordb"]

        ports:
        -   "${FALKORDB_PORT}:6379"  # FalkorDB (Redis protocol)
        -   "${FALKORDB_BROWSER_PORT}:3000" # FalkorDB Browser UI

        volumes:
        -   falkordb_data:/data

volumes:
    falkordb_data:
        driver: local
