services:
    falkordb:
        image: ${IMAGE_VERSION}
        restart: "no"
        profiles: ["${SPEC}.falkordb"]
        ports:
        -   "${FALKORDB_PORT}:6379"
        container_name: ${CONTAINER_NAME}
        volumes:
        -   ${STORE_FOLDER}/data:/data
